language: node_js
node_js: node
cache: yarn

before_install: yarn global add greenkeeper-lockfile@3

before_script: greenkeeper-lockfile-update

script: yarn run travis

after_script: greenkeeper-lockfile-upload
